name: pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Path
      run: |
        PWD=$(pwd)
        export PYTHONPATH=$PWD/src
        echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Unit Tests with pytest
      run: |
        python -m unittest -k test_service
    - name: Analysing the code with pylint
      run: |
        pylint --disable=C0114,C0415,W0718 $(git ls-files '*.py') --fail-under=7.5